DROP TABLE IF EXISTS CLIENTS;
CREATE TABLE CLIENTS (
ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
NAME VARCHAR(255),
ADDRESS VARCHAR(255)
);

DROP TABLE IF EXISTS PRODUCTS;
CREATE TABLE PRODUCTS (
  ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  TYPE VARCHAR(255),
  MODEL VARCHAR(255),
  PRICE FLOAT(10,2)
);

DROP TABLE IF EXISTS PURCHASES;
CREATE TABLE PURCHASES (
  ID INT AUTO_INCREMENT NOT NULL UNIQUE PRIMARY KEY,
  CL_ID INT,
  PROD_ID INT,
  AMOUNT INT(10),
  FOREIGN KEY(CL_ID) REFERENCES CLIENTS(ID),
  FOREIGN KEY(PROD_ID) REFERENCES PRODUCTS(ID)
);

DROP TABLE IF EXISTS WAREHOUSE;
CREATE TABLE WAREHOUSE (
  ID INT AUTO_INCREMENT NOT NULL UNIQUE PRIMARY KEY,
  PROD_ID INT,
  AMOUNT INT(10),
  FOREIGN KEY(PROD_ID) REFERENCES PRODUCTS(ID)
);

